### ISSUE TITLE
Cannot make under Ubuntu 16.04

### ISSUE THREAD

**Issue by fixups** [abrasive/spacefn-evdev#1]
When trying to make the project under an up to date Ubuntu 16.04, the linker reports the following undefined symbols:
  libevdev_uinput_write_event
  libevdev_next_event
  libevdev_new_from_fd
  libevdev_uinput_create_from_device
  libevdev_grab

I have installed libevdev-dev manually. libevdev2 was already installed on the system. I do have /dev/uinput.

The command "pkg-config --libs libevdev" outputs: "-levdev".

The version of libevdev2 that is installed is:
  Package: libevdev2
  Version: 1.4.6+dfsg-1

The version of libevdev-dev that is installed is:
  Package: libevdev-dev
  Version: 1.4.6+dfsg-1

Let me know if you need further information.

Thank you in advance.

**Comment by abrasive** [comment]
Should be fixed now! Can you give it a go?

**Comment by fixups** [comment]
Yes I can compile it now and the executable works as advertised.

Thanks!
