### ISSUE TITLE
Can't control cursor with external keyboards that have integrated touchpad or trackpoint

### ISSUE THREAD

**Issue by maciejmotyka** [abrasive/spacefn-evdev#2]
When I enable spacefn with Logitech K400+ (has a touchpad) or Lenovo ThinkPad Bluetooth keyboard (has a trackpoint), I can no longer move the cursor. All keys function ok, including the "mouse buttons" below the touchpad/trackpoint.
It seems to me that when spacefn is enabled the events of type 2 or "EV_REL" are being lost during the processing of keystrokes.
This does not cause any problems when using the built-in laptop keyboard and touchpad/trackpoint, because they are recognized as separate devices, so when the keyboard events stream is redirected to spacefn, the EV_REL commands are not. On the other hand, all of the commands that come from an external keyboard are mixed together in one stream of events. 
I run Ubuntu 19.04.

**Comment by abrasive** [comment]
Whoops, I'm not sure I meant to /close/ that just yet... would you mind testing the patch?

And thanks for the report!

**Comment by maciejmotyka** [comment]
Works great now with both keyboards. Thanks a ton!

**Comment by abrasive** [comment]
Great! Thanks for letting me know.
