### ISSUE TITLE
Mapping KEY_COMMA to tilde

### ISSUE THREAD

**Issue by ftassi** [abrasive/spacefn-evdev#5]
Hi thanks for your amazing work !
I'm trying to map the original spaceFN layout, but i cannot figure out how to map space + comma to ~ 

I looked for the right constant for the tilde key here, but I'm not able to find it. Do you know how to remap this key?

Thanks

**Comment by tmk** [comment]
You will have to send shift(`KEY_LEFTSHIFT`) and grave(`KEY_GRAVE`) to get `~` if you are on US keyboard. But this may vary depending on your keyobard layout.

https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/input-event-codes.h#L116

**Comment by ftassi** [comment]
Thanks @tmk. Yes I am using US layout, so `shift+grave` == `~`
I not sure how to modify the script to send a combination of keys instead of just one (I do not know C). key_map function accepts a key and map it to another one.

I do not actually need it though, because I already mapped spaceFN + m to do the grave, so I can just press spaceFN + m + shift and get the tilde. Seems reasonable to me, right now.  

Thanks again.
