### ISSUE TITLE
Running spacefn disables enter key

### ISSUE THREAD

**Issue by BrandonTrigueros** [abrasive/spacefn-evdev#9]
## What i did:
1. Download source zip into home directory and extract the package
2. Mapped KEY-L to KEY-RIGHT, KEY-I to KEY-UP, KEY-U to KEY-HOME, KEY-O to KEY-END and KEY-M to KEY-PAGEUP
3. Build the executable running the make command
4. run the program using the command `sudo ./spacefn /dev/input/by-id/usb-BY_Tech_Gaming_KB-event-kbd`

## Expected behavior:
spacefn layout is applied to mapped keys and other keys are unaffected

## Actual behavior:
1. Mapped keys worked as expected
2. Old keys stop working (due to blacklist function i assume)
3. Enter key stop working completely

**Note**: Same behavior if the command is `sudo ./spacefn /dev/input/eventXX`

**Comment by abrasive** [comment]
Hi mate! What can happen is that the enter key gets stuck "down" because you're holding it when spacefn starts.

What happens if you run

`sleep 1; sudo ./spacefn /dev/input/by-id/usb-BY_Tech_Gaming_KB-event-kbd`

so that you have time to let go of Enter before spacefn starts?

**Comment by BrandonTrigueros** [comment]
Hey man! Your deduction was correct. I was previously using spacefn in another ubuntu machine and it has been just wonderfull. I did not have the issue back then and i didn't really knew what was causing it but your suggestion worked perfectly. Thank you very much mate. Keep up with the amazing work!

**Comment by abrasive** [comment]
Thanks mate, glad it's helpful :D
